### ISSUE TITLE
SEV-SNP: Rack ROME2D16-2T hard locks

### ISSUE THREAD

**Issue by aep** [AMDESE/AMDSEV#140]
testing SNP on several systems with mixed results. mostly it works fine except the usual issues with abondoned old kernel forks.

A special case appears to be the ROME2D16-2T, i tried with an 7313 and a  7713

```
root@ns3229705:~# dmesg | grep  'SEV\|ccp'
[    5.745904] SEV-SNP: RMP table physical address 0x0000000035600000 - 0x0000000075bfffff
[   19.479814] ccp 0000:47:00.1: enabling device (0000 -> 0002)
[   19.479999] ccp 0000:47:00.1: no command queues available
[   19.480054] ccp 0000:47:00.1: sev enabled
[   19.480056] ccp 0000:47:00.1: psp enabled
[   19.720420] ccp 0000:47:00.1: SEV-SNP support requires firmware version >= 1:51
[   19.740503] ccp 0000:47:00.1: SEV: failed to INIT error 0x1, rc -5
[   19.749501] ccp 0000:47:00.1: SEV API:1.49 build:3
[   19.839876] SEV supported: 410 ASIDs
[   19.839877] SEV-ES and SEV-SNP supported: 99 ASIDs
```

```
rdmsr -x 0xc0010010
3fc0000
```

this seems to indicate that the SP is too old? but the same bios version works fine in a different machine.
Both asrock, and they're generally very lazy so i dont think there's much difference.

launch-qemu.sh immediately hard locks the cpu. vga blacks out.

```
root@ns3229705:~# cpuid | grep SEV
      SEV: secure encrypted virtualize support = true
      SEV-ES: SEV encrypted state support      = true
      number of SEV-enabled guests supported   = 0x1fd (509)
      minimum SEV guest ASID                   = 0x64 (100)

```

**Comment by tlendacky** [comment]
Is the other machine updating the firmware. The ccp driver will attempt to load new SEV firmware if it is present in the /lib/firmware/amd directory. It's possible that the other machine has a newer version of firmware in the filesystem. You can find the latest firmware at https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/amd

Also, 7xx3 parts are Milan parts, not Rome.

**Comment by aep** [comment]
rome is the motherboard name. idk why. this only happens on this board so i thought it might be relevant.

all machines have the latest firmware from https://developer.amd.com/sev/

**Comment by RARelph** [comment]
What is the base BIOS on the 2 machines?
Milan is pin-compatible with Rome, so I'm not surprised at the motherboard name.
However, the BIOSes for Rome and Milan are different.

**Comment by tlendacky** [comment]
> all machines have the latest firmware from https://developer.amd.com/sev/

That updated firmware is not being loaded (it is 1.54 and that machine is reporting 1.49) and, for various reasons, I would suggest that you use the version in the linux-firmware until your base firmware that comes with the BIOS is above 1.52.

**Comment by RARelph** [comment]
Right. As it says in the Milan Release Notes:
  The MinBLVersion is the minimum PSP Bootloader version that is required to run an SEV firmware image.
  The MinBLVersion gets updated when SEV relies on the the PSP Bootloader for a feature or a minimum Microcode version that was released with that PSP Bootloader.
  The goal is to never change this unless it's absolutely needed.
  Current Milan SEV/SNP FW requires a PSP BootLoader version of 00.13.00.70 or greater. Milan AGESA PI 1.0.0.9 included a sufficient PSP Boot Loader.
  Attempting to update to current SEV FW with an older BootLoader will fail.

    I suspect the machine it doesn't work on is running an "old" BIOS, the update to 1.54 fails, and you're left with the old BIOS's SEV FW, which isn't supported by the Linux SEV software.

**Comment by aep** [comment]
any idea how to get the current AGESA? i cant seem to find that information in BIOS.

> Current Milan SEV/SNP FW requires a PSP BootLoader version of 00.13.00.70 or greater

outch. i've got 00.13.00.6B. so that's probably it

![2023-03-02-180738_821x619_scrot](https://user-images.githubusercontent.com/136926/223157183-02dba2ba-df24-4f37-aa64-59f3152f9c10.png)

**Comment by RARelph** [comment]
Yup, that's it. You have 2 choices right now:
1) Do as Tom said and continue to use the Linux firmware tree's current SEV version
2) Update your BIOS, if ASRock makes a newer BIOS available for your system.

**Comment by tlendacky** [comment]
What are you trying to run? Looking at the output, you don't have any ASIDs available to SEV-ES/SEV-SNP. You need to go into your BIOS settings and change the minimum SEV ASID number to something greater than 1. If you want to support up to 100 concurrent SEV-ES/SEV-SNP VMs, then set the minimum SEV ASID to 101.

**Comment by aep** [comment]
aye, the original problem is solved.
lesson learned: sev firmware and bios versions need to be matched.

thanks a lot for your help.

**Comment by mmisono** [comment]
I had a similar issue on Supermicro H12DSG-O-CPU with the latest BIOS (revision 2.4). Updading firmware to 1.54 (from 1.49) failed.

```
[  489.661405] ccp:__sev_do_cmd_locked: ccp 0000:29:00.1: sev command 0xb failed (0x00000003)
[  489.661410] (out): 00000000: 0020 7cc2 0020 0000 54c0 0001
[  489.661411] ccp:sev_update_firmware: ccp 0000:29:00.1: Failed to update SEV firmware: 0x3
[  489.661417] ccp 0000:29:00.1: SEV-SNP support requires firmware version >= 1:51
```

And I tried firmware 1.51 found [here](https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/commit/amd/amd_sev_fam19h_model0xh.sbin?id=21a405e4623d91c673028f67404541afdcfbd056) and it worked. (updating to 1.54 from 1.51 still failed; probably we need to wait for BIOS updates)
